### ISSUE TITLE
script.js analytics not loading

### ISSUE THREAD

**Issue by tacman** [wes-goulet/background-noise#14]
The usefalcon cdn isn't loading.  I think it should be removed altogether, since it won't work if developing anyway without a key.

![image](https://github.com/wes-goulet/background-noise/assets/619585/ee7f8b94-0af1-489c-949e-fe44aa6a7eaf)

I'm experimenting with refactoring this app as a Symfony project and rendering the HTML via twig (mostly  as a learning exercise for me, since I'm very new to PWAs).  In that case, I would only render the analytics code if the api key were present in the environment variables, and it were production.  

But for now, it's not even working in production, so it distracts from this otherwise excellent example of  a PWA.

**Comment by wes-goulet** [comment]
I use fathom analytics to see how many people use the app.  It's privacy-focused for end users and very simple.  It might not be loading for you because your browser blocks it, which is fine.

I don't believe there is any actionable bug here so closing this out.

**Comment by tacman** [comment]
Ah, I see, when I run in incognito it does work, so indeed my browser must be blocking it.
